name = "BoisCraft"
author = "Womes"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d2031e725b18fa3ae1df95897541565f3a2b2f05e235de3b103830046859b2bb"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"

[options]
datapack-folder = "datapacks"
