name = "BoisCraft"
author = "Womes"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "272e93d26a011eaa145f467c14ba3a6ffd91c75aac8966f5865112811e642646"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"

[options]
datapack-folder = "datapacks"
