name = "BoisCraft"
author = "Womes"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "01496c783d9ca87c420ad67f59452b45db6e4a2238ba79c9b3211b47d815e6f4"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"

[options]
datapack-folder = "datapacks"
